### ISSUE TITLE
Back Button disappearing

### ISSUE THREAD

**Issue by Jamongkad** [GarethShapiro/SimpleIOSViewStackController#1]
Hello great little library you have here. Quick question when I make a transition to another controller. I see the Back button appear momentarily then disappear entirely. Can you please help me?

**Comment by GarethShapiro** [comment]
Thanks, it has served me well.  A Swift version is on the way ...

The reason the back button is disappearing is that by design the UIViewController you have moved away from is removed once the animation is finished.  This behaviour is a feature which helps you manage memory.

There are of course other features which will ensure that the UIViewController is not removed, take a look at this page of a tutorial on my website which explains it.

http://www.garethshapiro.com/item/simple-ios-viewstack/?page=4

You should note that this tutorial was made for an early version of SimpleIOSViewStackController and if you are using the latest one then also check out the updated tutorial for the best syntax once you have absorbed the concept.

http://www.garethshapiro.com/item/simple-ios-viewstack-3/?page=1

Let me know how you get on.

**Comment by Jamongkad** [comment]
Hi Gareth,

Thanks for the quick response. Thanks for the tip! Oh by the way I'm using Objective-C :)
